#!/usr/bin/env bash
# Setup a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo -e 'frontend web_servers_frontend
\tbind *:80
\tmode http
\tdefault_backend web_servers_backend

backend web_servers_backend
\tbalance roundrobin
\tserver 1803-web-01 35.243.134.103:80 check
\tserver 1803-web-02 34.75.53.215:80 check
' >> /etc/haproxy/haproxy.cfg
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo service haproxy restart
