#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
until ((i == 10))
do
    if ((i == 8))
    then
        echo "Holberton School"
        echo "Hi"
    else
        echo "Holberton School"
    fi
    ((i++))
done
