#!/usr/bin/env bash
# This script displays the current directory
# in list format where only part of the name
# after the first dash is displayed
for file in *
do
    echo "$file" | cut -d - -f 2-
done
